version: '3.8'

services:
    php:
        build:
            context: ./config/docker/local/php
            args:
                - HOST_UID=${HOST_UID}
        image: marketplace-shops-php
        container_name: marketplace-shops-php
        networks:
            net:
                aliases:
                    - marketplace-shops-php
            local:
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/local/php/docker-entrypoint.sh
        environment:
            - COMPOSER_HOME=/var/www/html/var/composer
            - PHP_IDE_CONFIG
            - APP_ENV
    nginx:
        build: ./config/docker/local/nginx
        image: marketplace-shops-nginx
        container_name: marketplace-shops-nginx
        networks:
            net:
                aliases:
                    - marketplace-shops-nginx
            local:
        depends_on:
            - php
        ports:
            - "${SERVER_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
networks:
    net:
        name: marketplace-net
    local:
        name: marketplace-shops-local
